# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    GROQ_API_KEY: '%env(GROQ_API_KEY)%'
    GROQ_API_URL: '%env(GROQ_API_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\GoogleCalendarService:
        arguments:
            $clientId: '%env(GOOGLE_CLIENT_ID)%'
            $clientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
            $redirectUri: '%env(GOOGLE_REDIRECT_URI)%'
            $serviceAccountPath: '%env(default::GOOGLE_SERVICE_ACCOUNT_PATH)%'
            $serviceAccountCalendarId: '%env(default::GOOGLE_SERVICE_ACCOUNT_CALENDAR_ID)%'

    App\Service\RecaptchaService:
        arguments:
            $secretKey: '%env(RECAPTCHA_SECRET_KEY)%'
    
    App\Service\WeatherService:
        arguments:
            $weatherApiKey: '%env(WEATHER_API_KEY)%'

    App\Service\SmsService:
        arguments:
            $twilioSid: '%env(TWILIO_SID)%'
            $twilioToken: '%env(TWILIO_TOKEN)%'
            $twilioPhone: '%env(TWILIO_PHONE)%'

    App\Service\AiService:
        arguments:
            $apiKey: '%env(GROQ_API_KEY)%'
            $apiUrl: '%env(GROQ_API_URL)%'

    # Alias to solve autowiring error in GoogleLoginController
    Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator: '@security.authenticator.form_login.main'
